Add models
ConstellationApps/Forms pull request #10
Opened 2017-03-14 01:16 UTC by dinoocch

This commit adds model functionality, as well as tests for each of the
features added.  In particular, I choose to use NoSQL elements in order
to speed up execution and make implementation easier.  Since we do not
need JOINS on element or submission information, the disadvantages of
NoSQL are greatly reduced.

In addition, this commit refactors the tests and continuous integration
to use Postgresql and configures flake8 to ignore automatically
generated migrations.

2017-03-14 03:08 UTC, dinoocch commented
| Name | Stmts | Miss | Cover |
|-|-|-|-|
| constellation_forms/models/form.py | 30 | 4 | 87% |
| constellation_forms/models/formSubmission.py | 37 | 3 | 92% |
| constellation_forms/models/validator.py | 16 | 2 | 88% |

2017-03-14 23:59 UTC, the-maldridge commented
In the validator slug you use the widget slug token instead of a specific one for the validator please change this before merging

2017-03-15 00:03 UTC, dinoocch commented
Whole docstring on that model was copy and pasted from widget.py and I forgot to update it. Fixed.

2017-03-15 00:06 UTC, the-maldridge commented
Ok. I'll put in a"review" when I'm back at my laptop so the merge will go
green. @m_wynn, you have final approval on this merge.

On Mar 14, 2017 7:03 PM, "Dino Occhialini" <notifications@github.com> wrote:

> Whole docstring on that model was copy and pasted from widget.py and I
> forgot to update it. Fixed.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ConstellationApps/Forms/pull/10#issuecomment-286600349>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACNtlgKwI1sIBj6FBQ8FaQsYQD10J0Hcks5rlyrpgaJpZM4McAuu>
> .
>

2017-03-15 00:17 UTC, m-wynn requested changes

2017-03-15 00:17 UTC, m-wynn commented on constellation_forms/models/__init__.py
> +Also requires `app_lable` and `db_table` to be set in Meta of model.
that can be deleted?  label?

2017-03-15 00:17 UTC, m-wynn commented on constellation_forms/models/formSubmission.py
> +                    raise ValidationError("Required element blank.")
These should be a different error message

2017-03-15 00:17 UTC, m-wynn commented on constellation_forms/tests/models/testFormSubmission.py
> +    def test_good_submission(self):
This could be cleaner if you put a lot of the duplicate code into a single function.  Thoughts @the-maldridge ?

2017-03-15 00:39 UTC, dinoocch commented on constellation_forms/models/__init__.py
> +Also requires `app_lable` and `db_table` to be set in Meta of model.
Deleted

2017-03-15 00:40 UTC, dinoocch commented on constellation_forms/models/formSubmission.py
> +                    raise ValidationError("Required element blank.")
Fixed.

2017-03-15 00:40 UTC, dinoocch commented on constellation_forms/tests/models/testFormSubmission.py
> +    def test_good_submission(self):
Code reuse reduced...

2017-03-15 00:43 UTC, m-wynn approved these changes

2017-03-15 01:26 UTC, the-maldridge approved these changes
All looks good except for the previously mentioned settings file comments.

2017-03-15 01:44 UTC, merged